name: Playwright CI

on:
  workflow_dispatch:
  repository_dispatch:
    types: [run-tests]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Ensure test-results directory exists
        run: mkdir -p test-results

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright in virtual display
        run: |
          xvfb-run npx playwright test --project=chromium ./tests/Website.spec.js || true

      - name: Verify JUnit report
        if: always()
        run: |
          if [ -f test-results/junit-report.xml ]; thengit status
            echo "JUnit report generated successfully."
          else
            echo "JUnit report not found. There might be an issue with report generation."
            exit 1
          fi

      - name: Check if JUnit Report exists
        run: ls -la test-results
